# Generated by Django 3.2 on 2021-04-22 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GG', '0003_announce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.CharField(max_length=15, null=True)),
                ('etime', models.CharField(max_length=15, null=True)),
                ('evenue', models.CharField(max_length=30, null=True)),
                ('edata', models.TextField(null=True)),
                ('datime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
