# Generated by Django 3.2 on 2021-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GG', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eping',
            field=models.TextField(null=True),
        ),
    ]
