# Generated by Django 3.2 on 2021-04-23 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GG', '0005_event_eping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='UReg',
        ),
    ]
