# Generated by Django 3.2 on 2021-04-24 02:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GG', '0006_rename_signup_ureg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UReg',
            new_name='Signup',
        ),
    ]
